### ISSUE TITLE
Typo Error in Fii-Cli doc that could mislead developers

### ISSUE THREAD

**Issue by erisanolasheni** [codefii/codefii#3]
@iamcoderisk  Hello, was checking your codeFii fii-cli doc at https://codefii.com/fii-cli when I noticed there's a mistake when trying to explain how to serve codeFii from port: The error is that you forgot to add the ```fii``` command before the ```--serve``` argument.
![codefii-doc](https://user-images.githubusercontent.com/6621375/44783148-65b08c00-ab81-11e8-9087-33c3f6f01255.png)

**Comment by iamcoderisk** [comment]
Hi, thank you for the report, can we talk on twitter let's know the way
forward? I use the same github username please send a DM.
Thanks

**Comment by erisanolasheni** [comment]
ok nice

**Comment by iamcoderisk** [comment]
The docs would be updated soon.
